// Generated from the client folders in the shared "Jayne Portfolio" Drive folder.
// To add a piece: drop the image in /public/portfolio and add an entry here.
// The first piece's image is used as the client's cover on the portfolio index.
// caseStudy is optional — only set it when a case study page exists for the client.

export type PortfolioPiece = {
  title: string;
  blurb: string;
  image: string;
  alt: string;
  width: number;
  height: number;
};

export type PortfolioClient = {
  slug: string;
  client: string;
  description: string;
  caseStudy?: string;
  pieces: PortfolioPiece[];
};

export const portfolioClients: PortfolioClient[] = [
  {
    slug: "pepsico",
    client: "PepsiCo®",
    description: "Closing the gap on a $250MM+ diverse spend.",
    caseStudy: "/case-studies/pepsico",
    pieces: [
      {
        title: "Campaign key visual",
        blurb: "A photography-led cover built on approved brand imagery rallies internal advocates around the shift from a supplier diversity program to an enterprise platform, with the style-guide approach keeping timing and approvals tight.",
        image: "/portfolio/pepsico-01.png",
        alt: "PepsiCo® — Campaign key visual",
        width: 1956,
        height: 1200,
      },
      {
        title: "Platform framework diagram",
        blurb: "A clean visual model positions the platform as the engine that turns a valued pipeline, disruptive innovation, and supply chain efficiency into impact beyond the supply chain, giving advocates a shared story to tell.",
        image: "/portfolio/pepsico-02.png",
        alt: "PepsiCo® — Platform framework diagram",
        width: 2338,
        height: 1436,
      },
      {
        title: "Business case slide",
        blurb: "This piece connects diverse spend to sales and revenue, framing supplier diversity as a commercial differentiator to build the enterprise-wide awareness needed to close the gap on $250MM+ in diverse spend.",
        image: "/portfolio/pepsico-03.png",
        alt: "PepsiCo® — Business case slide",
        width: 1952,
        height: 1196,
      },
      {
        title: "Program stats infographic",
        blurb: "A data-dense snapshot of the existing program, from $800MM in forecasted diverse spend to 335 suppliers across 23 categories, establishes the baseline the enterprise platform is built to grow.",
        image: "/portfolio/pepsico-00.png",
        alt: "PepsiCo® — Program stats infographic",
        width: 1954,
        height: 1198,
      },
    ],
  },
  {
    slug: "hornitos",
    client: "Hornitos® Tequila",
    description: "83% open rate. 79% attendance.",
    caseStudy: "/case-studies/hornitos",
    pieces: [
      {
        title: "Event announcement poster",
        blurb: "A poster announcing the Showtime premiere event anchored the campaign, giving NYC bartenders and consumers a rock-and-roll reason to show up and mix.",
        image: "/portfolio/hornitos-00.png",
        alt: "Hornitos® Tequila — Event announcement poster",
        width: 1218,
        height: 1582,
      },
      {
        title: "Event poster and mixology handbook system",
        blurb: "The premiere-night poster alongside the full grid of handbook spreads shows how a single event identity extended into the mixology education program that put the tequila in bartenders' hands.",
        image: "/portfolio/hornitos-04.png",
        alt: "Hornitos® Tequila — Event poster and mixology handbook system",
        width: 2858,
        height: 1622,
      },
      {
        title: "Mixology handbook cover",
        blurb: "The blackletter cover of the six-cocktail handbook, printed in gloss-on-matte black, carried the mixology training forward after the event as a keepsake for bartenders and guests.",
        image: "/portfolio/hornitos-01.png",
        alt: "Hornitos® Tequila — Mixology handbook cover",
        width: 1462,
        height: 1458,
      },
      {
        title: "Backlit poster installation",
        blurb: "Backlit campaign posters lined the venue walls, keeping the brand and its mixing message in view throughout the live bartender training event.",
        image: "/portfolio/hornitos-05.png",
        alt: "Hornitos® Tequila — Backlit poster installation",
        width: 1942,
        height: 1192,
      },
      {
        title: "Event collateral with signature cocktail",
        blurb: "Printed event materials photographed with one of the six signature cocktails connect the invitation-driven attendance to the drinks bartenders learned to build.",
        image: "/portfolio/hornitos-02.png",
        alt: "Hornitos® Tequila — Event collateral with signature cocktail",
        width: 1036,
        height: 692,
      },
      {
        title: "Printed invitation and handbook",
        blurb: "The screw-bound handbook and premiere invitation as produced pieces, the mailing that drove an 83 percent open rate and 79 percent attendance.",
        image: "/portfolio/hornitos-03.png",
        alt: "Hornitos® Tequila — Printed invitation and handbook",
        width: 1036,
        height: 690,
      },
    ],
  },
  {
    slug: "big-lots",
    client: "Big Lots!",
    description: "3X more shopping in store. 3X more shopping online.",
    pieces: [
      {
        title: "Category page with faceted search",
        blurb: "A desktop category page built around faceted browsing and deal discovery, putting the thrill of the search at the center of the retailer's first e-commerce experience.",
        image: "/portfolio/big-lots-00.png",
        alt: "Big Lots! — Category page with faceted search",
        width: 1126,
        height: 818,
      },
      {
        title: "E-commerce page design system",
        blurb: "Full-page comps for the homepage, trending landing page, and product detail page, showing the end-to-end shopping flow designed mobile-first and delivered two weeks early.",
        image: "/portfolio/big-lots-01.png",
        alt: "Big Lots! — E-commerce page design system",
        width: 1944,
        height: 1186,
      },
      {
        title: "Wireframe process diagram",
        blurb: "A map of the inputs behind each wireframe, from brand platform and requirements to use cases and shopping-mindset personas drawn from 13 million loyalty customers.",
        image: "/portfolio/big-lots-02.png",
        alt: "Big Lots! — Wireframe process diagram",
        width: 1946,
        height: 1192,
      },
    ],
  },
  {
    slug: "meatheads",
    client: "Meatheads",
    description: "Turned a “no way” into 79% willingness to try.",
    pieces: [
      {
        title: "Refreshed logo and promotional graphics",
        blurb: "The redesigned cow-and-wordmark identity anchors a suite of promotions, keeping the logo familiar to the average eye while carrying an entirely new emotional connection.",
        image: "/portfolio/meatheads-00.png",
        alt: "Meatheads — Refreshed logo and promotional graphics",
        width: 3202,
        height: 2016,
      },
      {
        title: "'Everybody wins' testimonial ad",
        blurb: "A kid's-eye confession about mom's favorite salad reframes the brand around made-to-order freshness, turning a skeptical audience's 'no way' into willingness to try.",
        image: "/portfolio/meatheads-01.png",
        alt: "Meatheads — 'Everybody wins' testimonial ad",
        width: 1486,
        height: 1936,
      },
      {
        title: "'#Dadurday' testimonial ad",
        blurb: "This print ad speaks in the family's own voice, pairing never-frozen credentials with a weekend ritual to shift how fast casual talks about its food.",
        image: "/portfolio/meatheads-02.png",
        alt: "Meatheads — '#Dadurday' testimonial ad",
        width: 826,
        height: 1074,
      },
      {
        title: "'Pineapple and avocado' testimonial ad",
        blurb: "A parent's handwritten endorsement puts customization front and center, replacing fast-food assumptions with the positive associations of fresh, made-to-order dining.",
        image: "/portfolio/meatheads-03.png",
        alt: "Meatheads — 'Pineapple and avocado' testimonial ad",
        width: 818,
        height: 1068,
      },
      {
        title: "Menu board system",
        blurb: "The in-store menu boards lead every category with quality claims like no additives and never frozen, making made-to-order the organizing idea of the ordering experience.",
        image: "/portfolio/meatheads-06.png",
        alt: "Meatheads — Menu board system",
        width: 1894,
        height: 742,
      },
      {
        title: "Limited-time-offer poster series",
        blurb: "Bold typographic posters for seasonal items extend the refreshed identity into a flexible promotional system built within the eight-week platform redesign.",
        image: "/portfolio/meatheads-05.png",
        alt: "Meatheads — Limited-time-offer poster series",
        width: 1886,
        height: 788,
      },
      {
        title: "Mobile web experience",
        blurb: "The mobile menu and location finder carry the new identity to the small screen, keeping quality messaging attached to every item from browse to visit.",
        image: "/portfolio/meatheads-08.png",
        alt: "Meatheads — Mobile web experience",
        width: 1730,
        height: 1144,
      },
      {
        title: "'Cowmunity Spotlight' in-store signage",
        blurb: "A monthly community-recognition program with banners, standees and social prompts infuses the brand with the positive, values-driven connotations the repositioning called for.",
        image: "/portfolio/meatheads-07.png",
        alt: "Meatheads — 'Cowmunity Spotlight' in-store signage",
        width: 1838,
        height: 1210,
      },
      {
        title: "Summer book tour event map",
        blurb: "An illustrated roadmap of eighteen family storytime events shows the repositioned brand living its values in the community rather than just claiming them.",
        image: "/portfolio/meatheads-04.png",
        alt: "Meatheads — Summer book tour event map",
        width: 3252,
        height: 1358,
      },
    ],
  },
  {
    slug: "county-care",
    client: "CountyCare",
    description: "150K+ applications completed.",
    pieces: [
      {
        title: "Bilingual poster and flyer series",
        blurb: "English and Spanish enrollment posters put real ER patients front and center with a plain-spoken promise of great health care at no cost, reframing how insurance and who pays for it gets talked about across cultures on the way to 150K+ completed applications.",
        image: "/portfolio/county-care-00.png",
        alt: "CountyCare — Bilingual poster and flyer series",
        width: 1942,
        height: 1190,
      },
      {
        title: "Window graphics and eligibility banners",
        blurb: "Large-format window clings and banners turned the health system's own hospital and clinic facades into its most valuable media, spelling out eligibility rules and a text-to-remind QR path exactly where prospective applicants already were.",
        image: "/portfolio/county-care-01.png",
        alt: "CountyCare — Window graphics and eligibility banners",
        width: 1944,
        height: 1184,
      },
      {
        title: "Real-patient portrait series",
        blurb: "A studio portrait series of actual ER patients gave the campaign its emotional backbone, grounding every touchpoint in the faces of the people the program was built to enroll.",
        image: "/portfolio/county-care-02.png",
        alt: "CountyCare — Real-patient portrait series",
        width: 1880,
        height: 994,
      },
    ],
  },
  {
    slug: "crisp-market",
    client: "Crisp Market",
    description: "76% likely to purchase. 89% repeat purchase.",
    pieces: [
      {
        title: "Kiosk Wrap and Free-Lunch Outreach Mailer",
        blurb: "Woodgrain kiosk graphics and a direct-mail free-lunch invitation that brought a fresh, restaurant-like presence into office lobbies and anchored the customer-centric outreach program that took the brand from zero awareness.",
        image: "/portfolio/crisp-market-00.png",
        alt: "Crisp Market — Kiosk Wrap and Free-Lunch Outreach Mailer",
        width: 1884,
        height: 1174,
      },
      {
        title: "Touchscreen Ordering Interface: Attract Screen Through Checkout",
        blurb: "The full self-service purchase flow, from the We Brought Lunch In attract screen to a 30-item menu grid and cart, delivering a restaurant-like experience that runs entirely on automation.",
        image: "/portfolio/crisp-market-01.png",
        alt: "Crisp Market — Touchscreen Ordering Interface: Attract Screen Through Checkout",
        width: 1904,
        height: 1106,
      },
      {
        title: "Kiosk UI Screen Suite: Menu Browse, Nutrition Detail, and Cart",
        blurb: "Supporting interface screens covering category browsing, item nutrition facts, and checkout, rounding out a self-service system that helped cut initial launch cost from $250K to $6K.",
        image: "/portfolio/crisp-market-02.png",
        alt: "Crisp Market — Kiosk UI Screen Suite: Menu Browse, Nutrition Detail, and Cart",
        width: 1918,
        height: 1116,
      },
    ],
  },
  {
    slug: "willow-research",
    client: "Willow Research",
    description: "From non-existent to award-winning.",
    pieces: [
      {
        title: "Primary Logo and Wordmark",
        blurb: "A layered, overlapping W built from translucent ribbons gives visual form to the winnowing methodology at the heart of the brand, delivered in under six weeks and recognized with a MarCom Gold award.",
        image: "/portfolio/willow-research-00.png",
        alt: "Willow Research — Primary Logo and Wordmark",
        width: 1954,
        height: 1194,
      },
      {
        title: "Website Homepage",
        blurb: "The homepage leads with the question 'What could you accomplish if you could get to the truth,' establishing the confident, inquisitive tone that carries the new identity from day one.",
        image: "/portfolio/willow-research-01.png",
        alt: "Willow Research — Website Homepage",
        width: 1948,
        height: 1192,
      },
      {
        title: "Approach Page, Desktop and Tablet",
        blurb: "Responsive layouts for the Approach page walk visitors through the step-by-step research process, exposing the layers and depth of the methodology that the brand was built to communicate.",
        image: "/portfolio/willow-research-02.png",
        alt: "Willow Research — Approach Page, Desktop and Tablet",
        width: 1954,
        height: 1194,
      },
      {
        title: "Interior Page System",
        blurb: "Leadership, Why Willow, and Expertise pages extend the identity into a consistent system of color-blocked headers, photography, and the 'power of truth' voice across the full site.",
        image: "/portfolio/willow-research-03.png",
        alt: "Willow Research — Interior Page System",
        width: 1946,
        height: 1186,
      },
    ],
  },
  {
    slug: "supply-hive",
    client: "Supply Hive",
    description: "A brand the CEO felt proud to present.",
    pieces: [
      {
        title: "Logo and tagline lockup",
        blurb: "The primary identity pairs a hive mark built from data bars with orbiting bees and the tagline \"Welcome to the Supplierverse,\" giving a serial entrepreneur's AI platform a simple, ownable story trademarked within six weeks.",
        image: "/portfolio/supply-hive-00.png",
        alt: "Supply Hive — Logo and tagline lockup",
        width: 3336,
        height: 1990,
      },
      {
        title: "Website homepage",
        blurb: "The homepage leads with the Supplierverse welcome and rings the product's feedback loop with reviews, ratings, machine learning, and AI, translating a complex data platform into a story the CEO can present in one screen.",
        image: "/portfolio/supply-hive-01.png",
        alt: "Supply Hive — Website homepage",
        width: 2370,
        height: 1884,
      },
      {
        title: "Product naming and hexagon system",
        blurb: "A honeycomb architecture organizes the platform into named, ownable products, including My Hive, Hive Reports, Ratings and Scores, and Matchmakers, making the obvious ownable across the offering.",
        image: "/portfolio/supply-hive-03.png",
        alt: "Supply Hive — Product naming and hexagon system",
        width: 3058,
        height: 1892,
      },
      {
        title: "Full site design and page system",
        blurb: "Interior pages and the full-scroll site carry the brand story from Insta-Insta-Intelligence to the founder narrative, showing how the identity flexes across every touchpoint of the channel strategy.",
        image: "/portfolio/supply-hive-02.png",
        alt: "Supply Hive — Full site design and page system",
        width: 2974,
        height: 1992,
      },
    ],
  },
  {
    slug: "ella",
    client: "Ella: Know Who You Are",
    description: "Launched a personal brand that secures celebrity day rates.",
    pieces: [
      {
        title: "Award-Winning Logo and Brand Identity",
        blurb: "An arched monogram in warm gold and orange, paired with the tagline \"Know Who You Are,\" gives the professor a standalone identity distinct from Tuck and ASCENT, and the work earned industry award recognition.",
        image: "/portfolio/ella-00.png",
        alt: "Ella: Know Who You Are — Award-Winning Logo and Brand Identity",
        width: 1948,
        height: 1202,
      },
      {
        title: "Responsive Personal Brand Website",
        blurb: "A desktop and mobile site leads with keynote footage and her own words on courage and voice, positioning her as a national speaker who commands celebrity day rates rather than a faculty page on someone else's domain.",
        image: "/portfolio/ella-01.png",
        alt: "Ella: Know Who You Are — Responsive Personal Brand Website",
        width: 1950,
        height: 1190,
      },
      {
        title: "Workshops, Speaking, and Bio Pages",
        blurb: "Interior pages package her customized programs, research credentials, and Fortune 100 client list into a clear commercial offer, turning her existing event calendar into an always-on marketing asset.",
        image: "/portfolio/ella-02.png",
        alt: "Ella: Know Who You Are — Workshops, Speaking, and Bio Pages",
        width: 1950,
        height: 1196,
      },
    ],
  },
  {
    slug: "syncrofy",
    client: "Syncrofy",
    description: "$850K in new sales within the first 6 months of repositioning.",
    pieces: [
      {
        title: "Two-Page Product Sell Sheet",
        blurb: "A digital sell sheet anchors the paperless sales kit, pairing real product screenshots with plain-language proof points so skeptical prospects can see that self-service EDI access actually exists.",
        image: "/portfolio/syncrofy-00.png",
        alt: "Syncrofy — Two-Page Product Sell Sheet",
        width: 1764,
        height: 1116,
      },
      {
        title: "Prospect-Facing Sales Presentation Deck",
        blurb: "A customizable pitch deck built from the same research-driven messaging walks decliners and adopters alike through the hybrid model, exception handling, and concrete next steps toward a trial.",
        image: "/portfolio/syncrofy-01.png",
        alt: "Syncrofy — Prospect-Facing Sales Presentation Deck",
        width: 1900,
        height: 882,
      },
    ],
  },
  {
    slug: "forevercar",
    client: "ForeverCar.com",
    description: "Reduced path to completed purchase to under 9 minutes.",
    pieces: [
      {
        title: "Value Proposition Explainer Slide",
        blurb: "A bold typographic frame that pulls the purchase path into the upfront of the marketing, framing lowest prices, upfront coverage details, and a simple four-step buying process as the lead message.",
        image: "/portfolio/forevercar-00.png",
        alt: "ForeverCar.com — Value Proposition Explainer Slide",
        width: 1954,
        height: 1204,
      },
      {
        title: "InstaQuote Vehicle Lookup Form",
        blurb: "The single-card quote form that opens the purchase path with a verified VIN lookup, built for repeat car owners who want to move from landing page to real pricing without a phone call.",
        image: "/portfolio/forevercar-03.png",
        alt: "ForeverCar.com — InstaQuote Vehicle Lookup Form",
        width: 1954,
        height: 1198,
      },
      {
        title: "Order Summary and Payment Walkthrough",
        blurb: "A guided checkout frame showing plan, deductible, and pay-in-full or installment options in one view, the final stretch of a flow that brings a completed purchase in under nine minutes.",
        image: "/portfolio/forevercar-02.png",
        alt: "ForeverCar.com — Order Summary and Payment Walkthrough",
        width: 1954,
        height: 1198,
      },
      {
        title: "Brand Logo End Card",
        blurb: "The closing end card pairs the wordmark and car linework with the URL, sending viewers straight from the marketing piece into the purchase path it just previewed.",
        image: "/portfolio/forevercar-01.png",
        alt: "ForeverCar.com — Brand Logo End Card",
        width: 1908,
        height: 1142,
      },
    ],
  },
  {
    slug: "remeter",
    client: "(RE)meter",
    description: "Multiple enterprise-level “testers” turned buyers.",
    pieces: [
      {
        title: "Brand Identity and Stationery System",
        blurb: "The core naming and identity work, with a meter-inspired logotype and traffic-light color mark carried across letterhead, business cards, and envelopes, gave a hard-to-explain data platform a brand worth buying into.",
        image: "/portfolio/remeter-03.png",
        alt: "(RE)meter — Brand Identity and Stationery System",
        width: 1944,
        height: 1190,
      },
      {
        title: "Credit-Score Rating Sales Collateral",
        blurb: "Rack cards and a gauge-style badge package the proprietary tenant-industry-lease rating as a familiar credit score, turning raw risk data into a product landlords could immediately understand and value.",
        image: "/portfolio/remeter-04.png",
        alt: "(RE)meter — Credit-Score Rating Sales Collateral",
        width: 1938,
        height: 1176,
      },
      {
        title: "Product Launch Campaign for Trade Show",
        blurb: "A coordinated print ad, preregistration email, and digital banner introduced a new subscription tool at RECon, showing how the platform brand was built to launch additional products under one system.",
        image: "/portfolio/remeter-00.png",
        alt: "(RE)meter — Product Launch Campaign for Trade Show",
        width: 1948,
        height: 1192,
      },
      {
        title: "Mobile App Interface and Icon",
        blurb: "Floating device mockups and an app icon present the rent-to-sales calculator as a polished on-the-go tool, the stabilized front end that helped enterprise testers see the platform as a real product.",
        image: "/portfolio/remeter-01.png",
        alt: "(RE)meter — Mobile App Interface and Icon",
        width: 1948,
        height: 1188,
      },
      {
        title: "Mobile UX Flow Screens",
        blurb: "Three sequential screens walk from ZIP and industry input to an instant ratio result and a tenant affordability calculator, the Bootstrap-based experience developed in parallel with the brand.",
        image: "/portfolio/remeter-02.png",
        alt: "(RE)meter — Mobile UX Flow Screens",
        width: 1944,
        height: 1192,
      },
    ],
  },
  {
    slug: "microautomation",
    client: "MicroAutomation",
    description: "Peace and calm for public safety's hardest transitions.",
    pieces: [
      {
        title: "\"Smooth Sailing\" Print Ad",
        blurb: "A lone sailboat on open water anchors this full-page ad, reassuring call takers and their directors that transitioning to a new call handling platform can be calm rather than disruptive.",
        image: "/portfolio/microautomation-00.png",
        alt: "MicroAutomation — \"Smooth Sailing\" Print Ad",
        width: 880,
        height: 1140,
      },
      {
        title: "\"Peace of Mind\" Print Ad",
        blurb: "An aerial bridge crossing carries the diagonal headline \"Peace of Mind\" straight into the campaign's core insight, speaking to the unspoken emotional driver of every PSAP facing an NG9-1-1 transition.",
        image: "/portfolio/microautomation-01.png",
        alt: "MicroAutomation — \"Peace of Mind\" Print Ad",
        width: 874,
        height: 1140,
      },
      {
        title: "\"In Harmony\" Print Ad",
        blurb: "A rowing crew in perfect sync visualizes the partnership message, positioning the vendor as a teammate that keeps technology, people and training aligned through the NG9-1-1 transition.",
        image: "/portfolio/microautomation-03.png",
        alt: "MicroAutomation — \"In Harmony\" Print Ad",
        width: 878,
        height: 1142,
      },
      {
        title: "\"Simple and Seamless\" Case Study Ad",
        blurb: "A tugboat guiding a container ship illustrates true partnership while the copy points hard-to-engage prospects to a real Baltimore County PSAP case study, one of the four investigation paths built into the campaign.",
        image: "/portfolio/microautomation-02.png",
        alt: "MicroAutomation — \"Simple and Seamless\" Case Study Ad",
        width: 878,
        height: 1144,
      },
    ],
  },
  {
    slug: "industrial-loss-consultants",
    client: "Industrial Loss Consultants",
    description: "Increased qualified lead generation by 22%.",
    pieces: [
      {
        title: "Process One-Sheet System",
        blurb: "A suite of black-and-yellow one-sheets that codifies the firm's reverse-engineering discovery questions, valuation steps, and call-to-back-to-production process, giving an unbranded player in a saturated market a provable, regulator-friendly argument at a glance.",
        image: "/portfolio/industrial-loss-consultants-00.png",
        alt: "Industrial Loss Consultants — Process One-Sheet System",
        width: 1986,
        height: 888,
      },
      {
        title: "Fire-Damaged Castings Line Case Study",
        blurb: "A two-page case study built like a white paper, walking a fire-damaged aluminum castings line from loss to restored production and closing on a repair-versus-replace table that documents 1.5 million dollars and five months saved.",
        image: "/portfolio/industrial-loss-consultants-01.png",
        alt: "Industrial Loss Consultants — Fire-Damaged Castings Line Case Study",
        width: 1708,
        height: 1096,
      },
      {
        title: "Explosion Recovery Case Study",
        blurb: "A field-photo-driven case study on rebuilding a saturator converting line after an explosion, using evidenced timelines and a 12 million dollar business-interruption saving to turn deep machine expertise into a technical argument for qualified leads.",
        image: "/portfolio/industrial-loss-consultants-02.png",
        alt: "Industrial Loss Consultants — Explosion Recovery Case Study",
        width: 1682,
        height: 1070,
      },
    ],
  },
];
